obstacle_range: 3.0  
raytrace_range: 4.0

# footprint: [[-0.45, -0.3], [-0.45, 0.3], [0.2, 0.3], [0.2, -0.35]] # Robot Size
# footprint: [[-0.45, -0.3], [-0.45, 0.3], [0.2, 0.3], [0.2, -0.3]]
footprint: [[-0.3, -0.3], [-0.3, 0.3], [0.3, 0.3], [0.3, -0.3]]

# inflation_radius: 1.75     # first try
# cost_scaling_factor: 2.58

# canon 5.9
# obstacle_range: 5.0
# raytrace_range: 6.0
# inflation_radius: 1.75
# cost_scaling_factor: 7.0

# gaepo
# obstacle_range: 0.0 #3
# raytrace_range: 0.0 #4
# inflation_radius: 0.0 #1
# cost_scaling_factor: 0.0 #3

# canon 04.24
# obstacle_range: 2.0
# inflation_radius: 0.4
# cost_scaling_factor: 10.0

map_type: costmap

# scan: {sensor_frame: front_lidar, data_type: LaserScan, topic: scan, marking: true, clearing: true}
obstacle_layer:  
  observation_sources: scan
  scan:
    data_type: LaserScan
    topic: scan
    marking: true
    clearing: true
    sensor_frame: front_lidar
  obstacle_range: 3.0  
  raytrace_range: 4.0



#cost_scaling_factor and inflation_radius were now moved to the inflation_layer ns
inflation_layer:
  enabled:              true
  cost_scaling_factor:  7.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.75  # max. distance from an obstacle at which costs are incurred for planning paths.

static_layer:
  enabled:              true
  map_topic:            /map
